In [1]:
import numpy as np
import pandas as pd

path = "weight-height.csv"
df = pd.read_csv(path)
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [2]:
df.isnull()
df.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [3]:
df.describe()

Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [4]:
array = np.array(df['Height'])
print(array)
print(type(array))

[73.84701702 68.78190405 74.11010539 ... 63.86799221 69.03424313
 61.94424588]
<class 'numpy.ndarray'>


In [5]:
weight = np.random.randint(1,60,size=len(array))
print(weight)

[59 22 59 ... 31 22 31]


In [6]:
weight_mean = np.average(df['Height'] , weights=weight)
print(weight_mean)

66.37581977326161


In [7]:
from scipy import stats
trimmed_mean = stats.trim_mean(df['Height'] , 0.1)
print(trimmed_mean)

66.3461565475659


In [9]:
hmean = stats.hmean(df['Height'])
print(hmean)

66.14402048148682


In [11]:
q1 = np.quantile(df['Height'] , 0.25)
q3 = np.quantile(df['Height'] , 0.75)
iqr = q3-q1;
print(iqr)

5.668641245615746


In [12]:
variance = np.var(df['Height'] , ddof=1)
print(variance)

14.803472640140777


In [13]:
skewness = stats.skew(df['Height'])
print(skewness)

0.04936168370490536


In [17]:
kurtosis = stats.kurtosis(df['Height'])
print(kurtosis)

-0.4744964699248557


In [18]:
data1 = np.random.rand(10)
print(data1)
data2 = np.random.rand(10)
print(data2)

[0.57640842 0.12588118 0.08234283 0.15623355 0.02125647 0.7402904
 0.75642567 0.20943147 0.87285705 0.73133867]
[0.72057547 0.61163973 0.55512598 0.12366363 0.70303714 0.47000772
 0.6391953  0.84145953 0.29182092 0.25677222]


In [19]:
correlation = np.corrcoef(data1,data2)
print(correlation)

[[ 1.         -0.29293229]
 [-0.29293229  1.        ]]


In [21]:
covariance = np.cov(data1,data2)
print(covariance)

[[ 0.11279382 -0.02276325]
 [-0.02276325  0.05353635]]
